In [2]:
import pandas as pd
import glob
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

import openai
from bertopic.representation import OpenAI

from hdbscan import HDBSCAN

In [3]:
df_news = pd.read_parquet('./Data/all_news_1984_2024.parquet')
df_news['Date'] = pd.to_datetime(df_news['Date'], format='%Y-%m-%d')

In [6]:
year = 1985

df_gpr = pd.read_csv(f"./Result/GPR_Peaks/data/gpr_peaks_{year}.csv")
filtered_news = df_news[df_news['Date'].isin(df_gpr['date'])]
filtered_news

,Date,Caption,Content
43420,1985-01-14,Pepper...and Salt: [2],Winter Shuffle It's the season of Sun Belt vac...
43421,1985-01-14,Pentagon's Authority to Get Audit Data From Co...,PITTSBURGH -- The federal government is toughe...
43422,1985-01-14,Pentagon Gets Right to Review Licensing Of Hig...,WASHINGTON -- President Reagan authorized the ...
43423,1985-01-14,Pennzoil Co.,"Pennzoil Co. (Houston) -- Norman J. Luke, grou..."
43424,1985-01-14,The Outlook: Interest Rates Seem Likely to Ris...,NEW YORK -- Last week's game of musical chairs...
...,...,...,...
80210,1985-12-31,Eurobonds in Marks Totaling $2.3 Billion Readi...,LONDON -- News that 23 borrowers are scheduled...
80211,1985-12-31,"Exchanges, Banks to Close Tomorrow for New Yea...","Stock and commodity exchanges, banks and most ..."
80212,1985-12-31,"Executives' Expectations For Quarter Low, Poll...",NEW YORK -- Dun & Bradstreet Corp. said busine...
80213,1985-12-31,Financing Business: Diversified Industries Inc.,DIVERSIFIED INDUSTRIES INC. said it entered in...
80214,1985-12-31,Futures Markets: Foreign Currencies Move Highe...,The Japanese yen led most other foreign curren...

In [12]:
for year in range(1985, 2025):
    # df_gpr = pd.read_csv(f"./Result/GPR_Peaks/data/gpr_peaks_{year}.csv")
    # filtered_news = df_news[df_news['Date'].isin(df_gpr['date'])]
    filtered_news = df_news[df_news['Date'].dt.year == year]
    print(year, len(filtered_news))

1985 37959
1986 35095
1987 38052
1988 36270
1989 44887
1990 56466
1991 54037
1992 65207
1993 59570
1994 86310
1995 57407
1996 44840
1997 75774
1998 43580
1999 45157
2000 40472
2001 34935
2002 32188
2003 34311
2004 37382
2005 37564
2006 30775
2007 2
2008 37407
2009 44268
2010 76178
2011 52632
2012 38660
2013 37409
2014 35628
2015 33628
2016 32492
2017 31734
2018 27612
2019 26820
2020 26900
2021 16397
2022 21173
2023 24371
2024 11834

In [28]:
docs = filtered_news['Content'].tolist()
timestamps = filtered_news['Date'].tolist()

# hdbscan_model = HDBSCAN(min_cluster_size=15, metric='euclidean', cluster_selection_method='eom', prediction_data=True)
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")
topic_model = BERTopic(embedding_model=embedding_model, 
                    #    min_topic_size=11,
                        nr_topics=35,
                       verbose=True)
topics, probs = topic_model.fit_transform(docs)
topic_info = topic_model.get_topic_info()
print("Topic Info:")
print(topic_info)
topic_model.visualize_topics(width=1000, height=1000)

2025-06-29 19:06:19,974 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/96 [00:00<?, ?it/s]

2025-06-29 19:06:23,019 - BERTopic - Embedding - Completed ✓
2025-06-29 19:06:23,019 - BERTopic - Dimensionality - Fitting the dimensionality reduction algorithm
2025-06-29 19:06:27,105 - BERTopic - Dimensionality - Completed ✓
2025-06-29 19:06:27,106 - BERTopic - Cluster - Start clustering the reduced embeddings
2025-06-29 19:06:27,145 - BERTopic - Cluster - Completed ✓
2025-06-29 19:06:27,145 - BERTopic - Representation - Extracting topics using c-TF-IDF for topic reduction.
2025-06-29 19:06:27,342 - BERTopic - Representation - Completed ✓
2025-06-29 19:06:27,343 - BERTopic - Topic reduction - Reducing number of topics
2025-06-29 19:06:27,347 - BERTopic - Representation - Fine-tuning topics using representation models.
2025-06-29 19:06:27,533 - BERTopic - Representation - Completed ✓
2025-06-29 19:06:27,534 - BERTopic - Topic reduction - Reduced number of topics from 58 to 35

Topic Info:
    Topic  Count                                          Name  \
0      -1    892                              -1_the_to_of_and
1       0    253                       0_israel_hamas_gaza_the
2       1    157                                1_the_to_in_of
3       2    136                              2_the_gas_oil_to
4       3    136                             3_mr_the_trump_he
5       4    123                             4_china_the_to_in
6       5    121                              5_the_to_that_of
7       6    108                  6_ukraine_russia_the_russian
8       7    107                              7_the_game_to_of
9       8     94                                8_ai_to_and_of
10      9     93           9_commentary_analysis_financial_and
11     10     83                       10_students_of_the_that
12     11     70                            11_drug_the_and_to
13     12     69                            12_trump_the_in_to
14     13     59                         13_office_home_the_in
15     14     54                           14_his_of_poe_pratt
16     15     50                  15_workers_strike_union_auto
17     16     49                  16_york_new_france_manhattan
18     17     46                              17_the_in_and_to
19     18     42                       18_fashion_brand_the_of
20     19     36                    19_disney_streaming_the_to
21     20     34                  20_ftx_bankman_fried_bitcoin
22     21     29                            21_the_said_and_of
23     22     28                   22_crested_saguaro_of_orman
24     23     27                             23_the_and_her_is
25     24     22                24_airlines_jsx_boeing_flights
26     25     19                   25_food_nutria_michelin_and
27     26     19                   26_abortion_pro_court_trump
28     27     17                          27_says_you_light_to
29     28     14                     28_magic_mike_tatum_movie
30     29     13              29_baime_barris_kustom_accelsius
31     30     13  30_realtors_association_national_commissions
32     31     13                        31_bear_goran_pink_and
33     32     10                    32_horwitz_emma_her_arnold
34     33     10                       33_value_banks_eve_bank

                                       Representation  \
0       [the, to, of, and, in, that, for, is, on, it]
1   [israel, hamas, gaza, the, israeli, of, and, i...
2   [the, to, in, of, and, year, its, for, market,...
3   [the, gas, oil, to, energy, in, of, and, for, ...
4   [mr, the, trump, he, to, house, and, his, in, of]
5   [china, the, to, in, and, of, chinese, is, for...
6   [the, to, that, of, in, for, tax, and, would, ...
7   [ukraine, russia, the, russian, to, of, and, i...
8     [the, game, to, of, he, in, it, that, his, and]
9       [ai, to, and, of, the, that, for, is, it, in]
10  [commentary, analysis, financial, and, , , , ,...
11  [students, of, the, that, to, and, university,...
12  [drug, the, and, to, for, of, drugs, in, that,...
13  [trump, the, in, to, his, mr, of, and, was, pr...
14  [office, home, the, in, to, of, rates, market,...
15  [his, of, poe, pratt, the, and, he, keats, is,...
16  [workers, strike, union, auto, uaw, the, ford,...
17  [york, new, france, manhattan, finland, estoni...
18  [the, in, and, to, that, city, of, crime, is, ...
19  [fashion, brand, the, of, and, vuitton, in, wi...
20  [disney, streaming, the, to, its, company, net...
21  [ftx, bankman, fried, bitcoin, crypto, exchang...
22  [the, said, and, of, in, were, was, to, disast...
23  [crested, saguaro, of, orman, the, to, pennock...
24  [the, and, her, is, music, of, in, with, opera...
25  [airlines, jsx, boeing, flights, airbus, jets,...
26  [food, nutria, michelin, and, restaurant, in, ...
27  [abortion, pro, court, trump, comstock, suprem...
28  [says, you, light, to, and, gym, she, exercise...
29  [magic, mike, tatum, movie, live, show, film, ...
30  [baime, barris, kustom, accelsius, turbo, asth...
31  [realtors, association, national, commissions,...
32  [bear, goran, pink, and, the, blue, farm, illu...
33  [horwitz, emma, her, arnold, she, students, re...
34  [value, banks, eve, bank, deposits, deposit, f...

                                  Representative_Docs
0   [Some managers in tech are experiencing -- man...
1   [Jerusalem -- The Biden administration has pur...
2   [Target Corp. said slower sales growth and ris...
3   [BIR REBAA, Algeria -- Once-obscure corners of...
4   [This is the season of Democratic discontent, ...
5   [The 2024 presidential race is the first since...
6   [On the eve of recessions in 1990, 2001 and 20...
7   [VILNIUS, Lithuania -- French President Emmanu...
8   [Brooks Koepka didn't sleep the Sunday night a...
9   [Almost out of the blue, it has become popular...
10  [[Financial Analysis and Commentary], [Financi...
11  [The first object of government, James Madison...
12  [Vivek Ramaswamy was a novice biotech entrepre...
13  [WASHINGTON -- President Biden spoke with the ...
14  [The U.S. is at risk of losing nearly 200,000 ...
15  ['Mission: Impossible -- Dead Reckoning Part O...
16  [The United Auto Workers strike at U.S. carmak...
17  [NEW YORK, NEW YORK, Tallinn, Estonia -- "You ...
18  [Last year, 327 career criminals were responsi...
19  [[Financial Analysis and Commentary] Fast fash...
20  [Walt Disney is exploring strategic options fo...
21  [A bipartisan group of U.S. senators said FTX'...
22  [GAZIANTEP, Turkey -- Aid poured into Turkey o...
23  [BUENOS AIRES -- Sergio Massa, the ruling part...
24  [Paul Simon has been putting out records for o...
25  [Flying these days is as enjoyable as a trip t...
26  [MUNICH -- Oktoberfest is usually all about th...
27  [Abortion opponents have mapped out a multipro...
28  [Are you giving it your all? Maybe that's too ...
29  [Film, Film, Miami -- Magic Mike Live is a mal...
30  [Joji Barris-Paster, owner of Barris Kustom, w...
31  [Your editorial "Realtors Face an Antitrust Re...
32  [OTOROHANGA, New Zealand -- As the sunrise cas...
33  [The first year in retirement is often the mos...
34  [WASHINGTON -- Top U.S. banking regulators str...

In [ ]:
# topic_model.reduce_topics(docs, nr_topics=20)
# topic_model.visualize_topics(width=500, height=500)

In [29]:
def topic_differences(model, original_topics, nr_topics=5):
    """Show the differences in topic representations between two models """
    df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
    for topic in range(nr_topics):

        # Extract top 5 words per topic per model
        og_words = " | ".join(list(zip(*original_topics[topic]))[0][:5])
        new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:5])
        df.loc[len(df)] = [topic, og_words, new_words]

    return df

from copy import deepcopy
original_topics = deepcopy(topic_model.topic_representations_)

prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following format:
topic: <short topic label>
"""

# Update our topic representations using GPT-3.5
client = openai.OpenAI(api_key="YOUR_OPENAI_API_KEY")

representation_model = OpenAI(
    client, model='gpt-4o' ,exponential_backoff=True, chat=True, prompt=prompt
)

topic_model.update_topics(docs, representation_model=representation_model)

# Show topic differences
topic_differences(topic_model, original_topics)

df_result = topic_model.get_topic_info()
df_result.to_csv('result_2.csv')

100%|██████████| 35/35 [00:40<00:00,  1.16s/it]

In [7]:
df_result

,Topic,Count,Name,Representation,Representative_Docs
0,-1,949,-1_Global Economic Uncertainty and Financial S...,[Global Economic Uncertainty and Financial Sec...,[Wall Street's traders and deal makers are str...
1,0,164,0_Political and Security Challenges in Israel ...,[Political and Security Challenges in Israel a...,[Palestine 1936 By Oren Kessler Rowman & Littl...
2,1,104,1_Sports Legends and Major Tournament Wins,[Sports Legends and Major Tournament Wins],[Brooks Koepka didn't sleep the Sunday night a...
3,2,104,2_2024 U.S. Presidential Election and Party Dy...,[2024 U.S. Presidential Election and Party Dyn...,"[This is the season of Democratic discontent, ..."
4,3,93,3_Global Energy Market Dynamics and Geopolitics,[Global Energy Market Dynamics and Geopolitics],[Russia said it plans to cut oil production by...
5,4,93,4_Financial Commentary and Analysis,[Financial Commentary and Analysis],"[[Financial Analysis and Commentary], [Financi..."
6,5,92,5_Ukraine-Russia War and International Diploma...,[Ukraine-Russia War and International Diplomat...,"[VILNIUS, Lithuania -- French President Emmanu..."
7,6,76,6_Financial Challenges and Strategic Shifts in...,[Financial Challenges and Strategic Shifts in ...,[Goldman Sachs Group Inc. Chief Executive Davi...
8,7,65,7_Economic Policy and Student Loan Reform,[Economic Policy and Student Loan Reform],[WASHINGTON -- An era of ultracheap debt is ov...
9,8,64,8_AI Impact and Ethical Considerations,[AI Impact and Ethical Considerations],[Seeing the new artificial intelligence-powere...
10,9,58,9_Challenges in the Pharmaceutical Industry an...,[Challenges in the Pharmaceutical Industry and...,[Politicians like to grouse about high drug pr...
11,10,49,10_UAW Strike and Labor Negotiations in the Au...,[UAW Strike and Labor Negotiations in the Auto...,[The United Auto Workers strike at U.S. carmak...
12,11,48,11_Electric Vehicle Market and Industry Dynamics,[Electric Vehicle Market and Industry Dynamics],[Tesla Inc. is considering more than $775 mill...
13,12,46,12_House Republican Leadership and Spending Bi...,[House Republican Leadership and Spending Bill...,[Hakeem Jeffries probably can't believe his lu...
14,13,45,13_Fashion Industry Trends and Brand Strategies,[Fashion Industry Trends and Brand Strategies],[[Financial Analysis and Commentary] Fast fash...
15,14,44,14_U.S. Semiconductor Industry and Government ...,[U.S. Semiconductor Industry and Government Po...,[[Financial Analysis and Commentary] The U.S. ...
16,15,41,15_China's Economic Challenges and Property Se...,[China's Economic Challenges and Property Sect...,[Xi Jinping has placed the Communist Party -- ...
17,16,38,16_Federal Reserve Interest Rate Policy and Ec...,[Federal Reserve Interest Rate Policy and Econ...,[Federal Reserve officials are set to hold int...
18,17,36,17_Literary Reflections on Iconic Writers and ...,[Literary Reflections on Iconic Writers and Hi...,"[['WHEN I HAVE FEARS' (1818), BY JOHN KEATS] I..."
19,18,35,18_Higher Education Challenges and Debates,[Higher Education Challenges and Debates],"[The first object of government, James Madison..."
20,19,34,19_Disney's Strategic Shifts in Theme Parks an...,[Disney's Strategic Shifts in Theme Parks and ...,[Walt Disney is exploring strategic options fo...
21,20,31,20_Legal Challenges and Investigations Surroun...,[Legal Challenges and Investigations Surroundi...,[Former Trump Organization finance chief Allen...
22,21,31,21_U.S. Stock Market Trends and Federal Reserv...,[U.S. Stock Market Trends and Federal Reserve ...,"[U.S. stocks inched slightly higher, with tech..."
23,22,31,22_Urban Challenges and Policy Responses in Ma...,[Urban Challenges and Policy Responses in Majo...,[Former New York Gov. Eliot Spitzer's ill-fate...
24,23,31,23_Disaster Response and Management in Turkey ...,[Disaster Response and Management in Turkey an...,"[GAZIANTEP, Turkey -- Aid poured into Turkey o..."
25,24,30,24_US-Iran Relations and Regional Tensions,[US-Iran Relations and Regional Tensions],[The Biden Administration was out in force on ...
26,25,28,25_Music and Performing Arts Innovations,[Music and Performing Arts Innovations],[Paul Simon has been putting out records for o...
27,26,28,26_Diverse Perspectives on Societal Exploratio...,[Diverse Perspectives on Societal Explorations...,"[BUENOS AIRES -- Sergio Massa, the ruling part..."
28,27,28,27_Detention of Wall Street Journal Reporter E...,[Detention of Wall Street Journal Reporter Eva...,"[Paul Whelan, the American held in Russia for ..."
29,28,27,28_Dining Experiences and Culinary Trends,[Dining Experiences and Culinary Trends],[MUNICH -- Oktoberfest is usually all about th...
30,29,27,29_US-Israel Relations and Political Dynamics,[US-Israel Relations and Political Dynamics],[Benjamin Netanyahu's delegation was shocked w...
31,30,24,30_European Travel and Political Developments,[European Travel and Political Developments],[Russia has sought to retrieve parts from defe...
32,31,23,31_Personal Development and Health Optimization,[Personal Development and Health Optimization],[Infrared light waves. Electromagnetic fields....
33,32,23,32_Retail and Stock Performance of Amazon and ...,[Retail and Stock Performance of Amazon and Ta...,[Target Corp. said slower sales growth and ris...
34,33,22,33_Hostage Negotiations and Fuel Deliveries in...,[Hostage Negotiations and Fuel Deliveries in G...,"[Hamas set free two more civilian hostages, bu..."
35,34,22,34_High-End Real Estate Sales and Relocations,[High-End Real Estate Sales and Relocations],"[A year after moving into the Washington, D.C...."
36,35,21,35_China-India Media Relations and Geopolitica...,[China-India Media Relations and Geopolitical ...,[SINGAPORE -- China's top diplomat began a fou...
37,36,21,36_Third-Quarter Profit and Revenue Trends in ...,[Third-Quarter Profit and Revenue Trends in Te...,[Royal Philips raised its full-year guidance a...
38,37,20,37_Airline Industry Challenges and Developments,[Airline Industry Challenges and Developments],[Flying these days is as enjoyable as a trip t...
39,38,19,38_Abortion Politics and Legal Strategies in t...,[Abortion Politics and Legal Strategies in the...,[Abortion opponents have mapped out a multipro...
40,39,19,39_FTX Collapse and Legal Proceedings,[FTX Collapse and Legal Proceedings],[A bipartisan group of U.S. senators said FTX'...
41,40,19,40_Fatherhood and Humor in Media,[Fatherhood and Humor in Media],"[Matthew McConaughey insists that ""the only"" r..."
42,41,19,41_Education Challenges and Reforms,[Education Challenges and Reforms],"[In ""Labor Unions Have Lost Their Way"" (op-ed,..."
43,42,18,42_Trends and Impacts of Long-term Bond Yields...,[Trends and Impacts of Long-term Bond Yields a...,[A deepening selloff in the U.S. bond market d...
44,43,18,43_Anti-Semitism and Moral Clarity in Universi...,[Anti-Semitism and Moral Clarity in Universities],[I am moved by University of Florida President...
45,44,17,44_Cryptocurrency Trends and Market Shifts,[Cryptocurrency Trends and Market Shifts],[[Financial Analysis and Commentary] Investors...
46,45,16,45_Gun Violence and Crime in the U.S.,[Gun Violence and Crime in the U.S.],[PITTSBURGH -- Prosecutors seeking the death p...
47,46,15,46_Elon Musk's Social Media Ventures and Biogr...,[Elon Musk's Social Media Ventures and Biograp...,[Elon Musk raised the idea of charging users o...
48,47,14,47_U.S.-China Relations and Indo-Pacific Marit...,[U.S.-China Relations and Indo-Pacific Maritim...,[The U.S. and Japanese navies have trained tog...
49,48,14,48_U.S. States and CosMc's Launch,[U.S. States and CosMc's Launch],"[ALABAMA, ALABAMA, BOLINGBROOK, Ill. -- CosMc'..."
50,49,13,49_Magic Mike Franchise and Live Shows,[Magic Mike Franchise and Live Shows],"[Film, Film, Miami -- Magic Mike Live is a mal..."
51,50,13,50_Housing Market and Mortgage Dynamics,[Housing Market and Mortgage Dynamics],[Home prices rose in March for the second stra...
52,51,13,51_New York City: Geography and Daily Life,[New York City: Geography and Daily Life],"[NEW YORK, NEW YORK, NEW YORK]"
53,52,13,52_Urban Dynamics and Post-Pandemic City Life,[Urban Dynamics and Post-Pandemic City Life],"[ERIE, Kan. -- As Chicago studies whether to b..."
54,53,13,53_Antitrust Issues in Real Estate Commissions,[Antitrust Issues in Real Estate Commissions],"[Your editorial ""Realtors Face an Antitrust Re..."
55,54,13,54_The Cult of Creativity and Ambition in Late...,[The Cult of Creativity and Ambition in Later ...,"[Fierce Ambition, The Cult of Creativity, The ..."
56,55,12,55_Corporate Influence and Holiday Culture,[Corporate Influence and Holiday Culture],"[We've twisted Christmas so many times, so man..."
57,56,11,56_Rising Apartment Rents and Housing Market C...,[Rising Apartment Rents and Housing Market Cha...,[If you want to know why apartment rents got s...
58,57,11,57_Instacart IPO and Market Developments,[Instacart IPO and Market Developments],[Instacart's shares jumped in their trading de...

In [8]:
topic_model.visualize_topics(width=500, height=500)