In [1]:
import pandas as pd
from bertopic import BERTopic
from sklearn.datasets import fetch_20newsgroups
from bertopic import BERTopic
from sentence_transformers import SentenceTransformer

import openai
from bertopic.representation import OpenAI

In [2]:
df_news = pd.read_parquet('./Data/news_date_-1_1.parquet')
df_news

,Date,Caption,Content
0,1984-12-31,Manager's Journal: Boosting Creativity and Dis...,An information-systems manager has assembled i...
1,1984-12-31,National Color Laboratories Inc.,"ROSELLE, N.J. -- National Color Laboratories I..."
2,1984-12-31,Massachusetts Agency Approves Textron Inc.'s P...,BOSTON -- The Massachusetts Division of Insura...
3,1984-12-31,Michigan General Corp.,Michigan General Corp. (Dallas) -- Bernard E. ...
4,1984-12-31,"Midway Air Shelves Helicopter Service Idea, Se...",WASHINGTON -- Midway Airlines dropped immediat...
...,...,...,...
98995,2020-03-25,Life & Arts: Hip-Hop in the Jazz Club,"Kassa Overall calls himself ""a backpack jazz p..."
98996,2020-03-25,Expose First Responders to the Coronavirus,Among many grim scenarios coming out of the co...
98997,2020-03-25,The Happy Few Are the Cured,The giddiest among us soon will be those who t...
98998,2020-03-25,Politics & Ideas: Covid-19 Relief Should Bar S...,As Covid-19 spreads and the economy falls off ...
98999,2020-03-25,Life & Arts -- My Ride: This T-Bird Has Seen I...,"Lonny Paul Johnson, 50, a musician and songwri..."

In [3]:
docs = df_news['Content'].tolist()
timestamps = df_news['Date'].tolist()

In [4]:
# 1. 选择一个预训练的嵌入模型
# 'all-MiniLM-L6-v2' 是一个速度和性能都很均衡的通用模型
embedding_model = SentenceTransformer("all-MiniLM-L6-v2")

# 2. 初始化 BERTopic 模型
# verbose=True 会在训练时打印进度信息
# embedding_model 参数指定了我们选择的嵌入模型
topic_model = BERTopic(embedding_model=embedding_model, 
                       min_topic_size=230,
                       verbose=True)

# 3. 训练模型并提取主题
# fit_transform 会返回每个文档对应的主题编号
# 对于有时间戳的数据，可以直接传入 timestamps 参数
topics, probs = topic_model.fit_transform(docs)

2025-06-28 02:10:03,197 - BERTopic - Embedding - Transforming documents to embeddings.

Batches:   0%|          | 0/3094 [00:00<?, ?it/s]

KeyboardInterrupt:

In [5]:
# 获取主题的概览信息
# Count: 该主题下的文档数量
# Name: BERTopic自动生成的主题名称（由前4个关键词和下划线组成）
# Representation: 代表该主题的关键词列表
topic_info = topic_model.get_topic_info()
print("Topic Info:")
print(topic_info)

# 主题-1是离群点，即模型认为不属于任何特定主题的文档。
# 我们可以看到每个主题的大小，方便我们关注那些规模较大的主题。

Topic Info:
    Topic  Count                                    Name  \
0      -1  43114                         -1_the_to_of_in
1       0   4378                          0_the_to_in_of
2       1   3294                         1_tax_the_to_mr
3       2   3218               2_airlines_airline_the_to
4       3   2451                     3_and_the_food_wine
5       4   2419                       4_the_to_cable_of
6       5   2158            5_drug_patients_drugs_cancer
7       6   2117                       6_mr_the_firm_sec
8       7   1987                         7_the_in_and_of
9       8   1983                      8_ford_car_auto_gm
10      9   1763              9_gas_power_energy_million
11     10   1706                      10_the_he_game_his
12     11   1475                 11_china_chinese_the_in
13     12   1392         12_president_named_officer_vice
14     13   1303          13_students_school_schools_the
15     14   1297                     14_and_the_music_of
16     15   1206              15_oil_opec_prices_barrels
17     16   1092            16_shares_common_million_via
18     17    959                     17_the_and_of_water
19     18    948                18_in_economy_the_prices
20     19    919              19_argentina_the_brazil_to
21     20    902                  20_stocks_or_stock_dow
22     21    879             21_japan_japanese_tokyo_yen
23     22    874        22_wireless_phone_verizon_sprint
24     23    804              23_anthrax_sars_health_the
25     24    788           24_russia_russian_ukraine_the
26     25    773              25_bank_million_first_said
27     26    724                    26_art_museum_of_and
28     27    693          27_ibm_intel_computer_software
29     28    654          28_fund_funds_investors_mutual
30     29    636       29_health_care_medicare_insurance
31     30    607             30_dollar_yen_currency_euro
32     31    607                  31_stores_mart_wal_and
33     32    553              32_basis_points_priced_via
34     33    545          33_million_share_quarter_cents
35     34    528           34_stores_sales_million_cents
36     35    517            35_bond_bonds_yield_treasury
37     36    491                    36_police_mr_was_the
38     37    390             37_facebook_to_google_users
39     38    383                       38_vol_yr_yld_its
40     39    367    39_options_puts_contracts_volatility
41     40    362                      40_book_his_of_and
42     41    361         41_korea_north_korean_pyongyang
43     42    358          42_euros_billion_french_francs
44     43    345  43_tobacco_cigarette_cigarettes_morris
45     44    341       44_contract_corp_million_aircraft
46     45    322            45_moody_rating_debt_ratings
47     46    316                   46_cents_or_small_cap
48     47    302            47_yen_billion_toshiba_japan
49     48    296                     48_she_her_says_job
50     49    287                49_euro_ecb_european_the
51     50    284         50_hospital_health_care_million
52     51    266                     51_trade_wto_the_to
53     52    265             52_africa_south_anc_african
54     53    265         53_steel_million_steelmaker_ltv
55     54    264      54_workers_jobs_unemployment_labor
56     55    241        55_mortgage_loans_loan_mortgages
57     56    231             56_fed_rates_rate_inflation

                                       Representation  \
0       [the, to, of, in, and, for, that, is, it, on]
1      [the, to, in, of, and, iraq, that, is, mr, on]
2      [tax, the, to, mr, of, that, and, in, for, is]
3   [airlines, airline, the, to, of, and, air, in,...
4     [and, the, food, wine, of, in, to, it, for, is]
5    [the, to, cable, of, and, in, for, tv, mr, news]
6   [drug, patients, drugs, cancer, the, of, to, i...
7   [mr, the, firm, sec, to, of, enron, and, that,...
8   [the, in, and, of, to, for, hotel, estate, new...
9   [ford, car, auto, gm, cars, vehicles, the, chr...
10  [gas, power, energy, million, oil, the, said, ...
11  [the, he, game, his, team, and, in, season, to...
12  [china, chinese, the, in, hong, kong, beijing,...
13  [president, named, officer, vice, chief, execu...
14  [students, school, schools, the, of, and, to, ...
15   [and, the, music, of, his, in, is, with, he, as]
16  [oil, opec, prices, barrels, crude, energy, th...
17  [shares, common, million, via, stock, inc, com...
18  [the, and, of, water, to, in, that, environmen...
19  [in, economy, the, prices, of, spending, econo...
20  [argentina, the, brazil, to, of, in, governmen...
21  [stocks, or, stock, dow, fell, market, rose, t...
22  [japan, japanese, tokyo, yen, the, to, in, of,...
23  [wireless, phone, verizon, sprint, service, to...
24  [anthrax, sars, health, the, vaccine, disease,...
25  [russia, russian, ukraine, the, putin, soviet,...
26  [bank, million, first, said, loan, of, corp, b...
27  [art, museum, of, and, the, in, his, artists, ...
28  [ibm, intel, computer, software, of, the, its,...
29  [fund, funds, investors, mutual, stock, stocks...
30  [health, care, medicare, insurance, the, to, c...
31  [dollar, yen, currency, euro, late, the, again...
32  [stores, mart, wal, and, sales, store, to, the...
33  [basis, points, priced, via, coupon, due, fees...
34  [million, share, quarter, cents, net, earnings...
35  [stores, sales, million, cents, share, quarter...
36  [bond, bonds, yield, treasury, market, treasur...
37  [police, mr, was, the, he, said, in, and, offi...
38  [facebook, to, google, users, the, mail, and, ...
39  [vol, yr, yld, its, dow, to, dj, nasdaq, aig, ...
40  [options, puts, contracts, volatility, calls, ...
41  [book, his, of, and, the, is, books, he, her, in]
42  [korea, north, korean, pyongyang, nuclear, sou...
43  [euros, billion, french, francs, million, prof...
44  [tobacco, cigarette, cigarettes, morris, phili...
45  [contract, corp, million, aircraft, navy, rece...
46  [moody, rating, debt, ratings, single, said, c...
47  [cents, or, small, cap, stocks, nyse, quarter,...
48  [yen, billion, toshiba, japan, profit, sales, ...
49  [she, her, says, job, women, you, to, and, ms,...
50  [euro, ecb, european, the, germany, europe, in...
51  [hospital, health, care, million, baxter, shar...
52  [trade, wto, the, to, tariffs, eu, countries, ...
53  [africa, south, anc, african, the, of, and, in...
54  [steel, million, steelmaker, ltv, corp, compan...
55  [workers, jobs, unemployment, labor, in, the, ...
56  [mortgage, loans, loan, mortgages, borrowers, ...
57  [fed, rates, rate, inflation, economy, greensp...

                                  Representative_Docs
0   [NEW YORK -- The hot market for new issues has...
1   [Tantalizing hints are surfacing about the ide...
2   [WASHINGTON -- One of the biggest lessons Pres...
3   [A multibillion-dollar airline-bailout package...
4   [AS WE'VE BEEN SAYING for so long, this is a t...
5   [WASHINGTON -- Federal regulators approved the...
6   [BELLEVILLE, Ill. -- Jacqueline Racener's doct...
7   [Capping a series of stunning disclosures, Art...
8   [Over the past few years, Americans have had a...
9   [DETROIT -- U.S. auto sales in November rose 7...
10  [VANCOUVER -- Canada, having achieved hefty ga...
11  [A year ago, Devean George was a good story th...
12  [HONG KONG -- While pro-democracy demonstrator...
13  [ANALOGIC Corp. (Peabody, Mass.) -- John W. Wo...
14  [JOE BRANCH LOOKED like a great catch -- much ...
15  [WHEN YOU FIND a movie you love, your first in...
16  [OSAKA, Japan -- The Organization of Petroleum...
17  [WASHINGTON -- The following issues were filed...
18  [WASHINGTON -- The Bush administration, often ...
19  [A surge in retail sales and hiring suggests t...
20  [BUENOS AIRES -- President Fernando de la Rua ...
21  [CONSUMERS SPENT more than expected in stores ...
22  [Many managers of international mutual funds b...
23  [NEW YORK -- Sprint Corp. broke off talks with...
24  [Investigators are giving a bleak assessment o...
25  [The U.S. and its European allies vowed Sunday...
26  [Losses widened at two big but weak Southweste...
27  [The year 2009 was an uncomfortable one for th...
28  [International Business Machines Corp. plans n...
29  [WASHINGTON -- The stocks of many publicly tra...
30  [Major health insurers in some states are seek...
31  [NEW YORK -- As the dollar wheezed its way acr...
32  [THE OFFICIAL CHRISTMAS shopping season hasn't...
33  [The following were among yesterday's offering...
34  [Johnson Controls Inc. said its fiscal second-...
35  [Stein Mart Inc. said a decline in same-store ...
36  [NEW YORK -- Encouraged by lower oil prices, i...
37  [NEWARK, N.J. -- When Mary F. Smith's car was ...
38  [Privacy wasn't a concern for her until it was...
39  [THE AMERICAN AIRLINES CRASH was another jolt ...
40  [NEW YORK -- Options investors looking for a c...
41  [[Eisenhower. Shakespeare. So much for light b...
42  [WASHINGTON -- Bush administration officials r...
43  [Suez SA reported a hefty net loss in 2002 des...
44  [NEW YORK -- Food and tobacco company Philip M...
45  [WASHINGTON -- Caltex Oil Products Co., 50%-ow...
46  [FOR THE PAST three years, the best way to mak...
47  [NEW YORK -- Small-cap stocks continued their ...
48  [TOKYO -- Huge losses at Toshiba Corp. and Fuj...
49  [Look at the names and pictures in almost any ...
50  [Frankfurt -- IN THE STRUGGLE to boost the glo...
51  [EVANSTON, Ill. -- American Hospital Supply Co...
52  [DOHA, Qatar -- During a closed-door meeting h...
53  [The journalist and black nationalist leader M...
54  [The nation's No. 1 and No. 3 steelmakers are ...
55  [Even as some economists declare the recession...
56  [THE MORTGAGE BOOM is back -- with a vengeance...
57  [WASHINGTON -- Barring an unanticipated accele...

In [21]:
fig1 = topic_model.visualize_topics(width=1000, height=1000)
fig1.show()

In [7]:
# 可视化主题-关键词关系图
# 这张图可以清晰地看到每个主题的关键词及其重要性
fig1 = topic_model.visualize_barchart(top_n_topics=12) # 可视化前12个最频繁的主题
fig1.show()

# 可视化主题间的相似度矩阵
# 帮助我们理解不同主题之间的关联性
fig2 = topic_model.visualize_heatmap(n_clusters=11, top_n_topics=12)
fig2.show()

In [8]:
def topic_differences(model, original_topics, nr_topics=5):
    """Show the differences in topic representations between two models """
    df = pd.DataFrame(columns=["Topic", "Original", "Updated"])
    for topic in range(nr_topics):

        # Extract top 5 words per topic per model
        og_words = " | ".join(list(zip(*original_topics[topic]))[0][:5])
        new_words = " | ".join(list(zip(*model.get_topic(topic)))[0][:5])
        df.loc[len(df)] = [topic, og_words, new_words]

    return df

In [9]:
from copy import deepcopy
original_topics = deepcopy(topic_model.topic_representations_)

In [12]:
prompt = """
I have a topic that contains the following documents:
[DOCUMENTS]

The topic is described by the following keywords: [KEYWORDS]

Based on the information above, extract a short topic label in the following format:
topic: <short topic label>
"""

# Update our topic representations using GPT-3.5
client = openai.OpenAI(api_key="YOUR_OPENAI_API_KEY")

representation_model = OpenAI(
    client, model='gpt-4o' ,exponential_backoff=True, chat=True, prompt=prompt
)

topic_model.update_topics(docs, representation_model=representation_model)

# Show topic differences
topic_differences(topic_model, original_topics)

100%|██████████| 58/58 [02:07<00:00,  2.20s/it]

,Topic,Original,Updated
0,0,the | to | in | of | and,U.S. Military Strategy and Diplomacy in Middle...
1,1,tax | the | to | mr | of,U.S. Tax Policy and Political Challenges
2,2,airlines | airline | the | to | of,U.S. Airline Industry Post-9/11 Economic Impac...
3,3,and | the | food | wine | of,Wine Recommendations and Culture
4,4,the | to | cable | of | and,AOL Time Warner Merger and Media Industry Chal...

In [20]:
# Save the model using safetensors
topic_model.save("model_dir", serialization="safetensors")

In [19]:
df_result = topic_model.get_topic_info()
df_result.to_csv('result_1.csv')